- example/lib/main.dart
- lib/network/parse_query.dart
- lib/objects/parse_user.dart
Added limit, skip etc, Fixed current user
> Added limit, skip etc, Fixed current user

- lib/src/data/parse_core_data.dart
changed to use variable clientkey instead master key
> set client key instead master key

- lib/src/objects/parse_user.dart
Fixed Parse login requests not working due to incorrect request type
> Fix Parse User Login

- README.md
Just mention the new global parameter in the readme file.
> Add autoSendSessionId parameter to README.md

- lib/src/objects/parse_object.dart
BugFix: Counters e Array Operations
> BugFix: Counters e Array Operations

- lib/src/objects/parse_object.dart
Bugfix Counters (increment / decrement)
> Bugfix Counters (increment / decrement)

- .gitignore
- lib/src/base/parse_constants.dart
- lib/src/objects/parse_base.dart
- lib/src/objects/parse_file.dart
- lib/src/objects/parse_geo_point.dart
- lib/src/objects/parse_installation.dart
- lib/src/objects/parse_object.dart
- lib/src/objects/parse_user.dart
- lib/src/utils/parse_encoder.dart
- lib/src/utils/parse_logger.dart
All changes have been tested and I am updating the Sample Code and Documentation;
List of changes:
Query Using Pointers Now Work
BugFix - Installation
- Update Endpoint
- New methods subscribeToChannel; unsubscribeFromChannel; getSubscribedChannels
BugFix - ParseFile upload;
Path update - Path its wrong
Method ParseFile.upload is a Future now for check result
BugFix - ParseGeopoint Encode
BugFix - ParseObject Encode
BugFix - ParseUser Encode
BugFix - ParseTypes encode (DateTime, Uint8List, ParseObject)
ParseObject - 
Update original Object with objectId after create
Deprecated Methods for Array e Counter
remove
removeAll
addAll
addUnique
add
increment
decrement
New methods similar to Native Parse to use in save()
setRemove
setRemoveAll
setAddAll
setAddUnique
setAdd
setIncrement …
> Many BugFix and New Functions ParseInstallation and ParseObject

- lib/src/network/parse_live_query.dart
- lib/src/objects/parse_object.dart
BugFix ParseObject Save and LiveQuery
> BugFix ParseObject Save and LiveQuery

- lib/src/network/parse_live_query.dart
- lib/src/objects/parse_object.dart
> Bugfix create object

- lib/src/network/parse_live_query.dart
> Bugfix LiveQuery

- .travis.yml
- pubspec.yaml
> Add Travis CI

- README.md
Please setup this repo on https://travis-ci.org.
I don't have permission to setup CI for this repo.
I had done it on my fork:
> add build status.

- lib/src/network/parse_query.dart
- pubspec.yaml
- test/parse_query_test.dart
Added the whereRelatedTo query for Parse Relations including unit test
> Implemented whereRelatedTo query

- lib/src/storage/core_store_sem_impl.dart
fix core corestore path 
if db password changed , the db will remove and return new instance
> fix corestore db on desktop 

- lib/src/objects/parse_base.dart
> Fix a stupid mistake.

- lib/src/objects/parse_base.dart
> Fix ACL save (#226)

- .gitignore
- lib/src/objects/parse_session.dart
hi!
I find a BUG when I want retrieving sessions,and I Fix it
before：
```
url = http://171.11.60.130/parse/sessions/me
```
now:
```
url = http://171.11.60.130:8000/parse/sessions/me
```
look forward to your reply，have a good day!
> Fix About Retrieving Sessions

- LICENSE
- lib/src/objects/parse_acl.dart
> Fixed permission for ACL's getWriteAccess

- lib/src/network/parse_live_query.dart
- pubspec.yaml
LiveQuery supports reconnection automatically.
> Optimize LiveQuery

- CHANGELOG.md
- README.md
- lib/parse_server_sdk.dart
- lib/src/base/parse_constants.dart
- pubspec.yaml
I have been struggling with finding a way to update the values of the existing object. After many trials and errors, I finally found it.
I added the example. I think it will be useful for anyone who is new to the SDK. Maybe my example needs some correction.
Thank you.
> Added an example of how to update existing object values

- lib/src/network/parse_live_query.dart
Should fix the issue described in #315 and improve the reconnecting after a connection loss to the live-query-server.
Please consider merging.
Cheers
> Livequery reconnecting controller

- lib/src/storage/core_store_sem_impl.dart
- pubspec.yaml
See: https://github.com/parse-community/Parse-SDK-Flutter/issues/321#issue-576574198
I just created this PR in case this changes are considered to be good.
> Fix for Sembast-API change

- lib/src/utils/parse_encoder.dart
As described in https://github.com/parse-community/Parse-SDK-Flutter/issues/325#issuecomment-597115126.
Should Fix #325
> added ParseACL to parseEncode

- example_livelist/lib/application_constants.dart
- example_livelist/lib/main.dart
- lib/src/utils/parse_live_list.dart
This is the change mentioned in https://github.com/parse-community/Parse-SDK-Flutter/pull/324#issuecomment-596952160
> ParseLiveList Performance improvement

- lib/src/objects/parse_base.dart
- lib/src/objects/parse_object.dart
This feature was requested in #318 
There should be no conflict with other parts of the sdk.
Do you want to merge it?
> Clear unsaved changes

- lib/src/utils/parse_live_list.dart
When I changed the itemBuilder to use a snapshot, I forgot to change the defaultItemBuilder.
> LiveList: fixed defaultBuilder

- lib/src/storage/core_store_sem_impl.dart
- pubspec.yaml
update core_store_sem_impl to the new implementation
> update sembsat to version 2.3.0

- README.md
Forgot to change the readme some time ago.
Should I create a PR to master as well?
> Update README - ParseLiveListWidget: snapshot in childbuilder

- lib/parse_server_sdk.dart
Seems like I forgot to commit one change.
> Fix getInstance of CoreStoreSembastImp

- .travis.yml
- packages/flutter/lib/parse_server_sdk.dart
As all files moved, the travis tests currently fail.
> fixing travis tests

- packages/dart/lib/src/objects/parse_user.dart
Added @BaranMichal25 fix for #456.
https://github.com/parse-community/Parse-SDK-Flutter/issues/456#issue-707407672
> fix for issue #456

- docs/migrate-1-0-28.md
Added section for tests at migration guide.
Fix: https://github.com/parse-community/Parse-SDK-Flutter/issues/385#issuecomment-695939265
> Update migrate-1-0-28.md | Added section for tests

- packages/dart/lib/src/objects/parse_user.dart
Improves the object to perform the Login using the POST method as a request.
> Change default login and signin method to POST #542

- packages/dart/lib/src/objects/parse_user.dart
Reverts parse-community/Parse-SDK-Flutter#544
> Revert "Change default login and signin method to POST #542"

- packages/dart/lib/src/objects/parse_user.dart
Change to the method to POST in the Login object to make the request to the Parse Server.
**Resolved issue**: [https://github.com/parse-community/Parse-SDK-Flutter/pull/544#issuecomment-758679406](https://github.com/parse-community/Parse-SDK-Flutter/pull/544#issuecomment-758679406)
> Change to the method to POST in the Login

- packages/flutter/lib/src/utils/parse_live_grid.dart
- packages/flutter/lib/src/utils/parse_live_list.dart
This allows you to add your own widget to an empty ParseLiveList or ParseLivegrid.
> Empty Query Widget ParseLiveList

- packages/flutter/README.md
How to use the ParseUser.forQuery() function
> Added details about querying for users

- packages/dart/README.md
- packages/flutter/README.md
#662 Fixed a typo, this PR updates the README accordingly.
Related issue: #661
> docs: fix typo in README

- .github/workflows/ci.yml
- move lint into separate job
- use caching for flutter download
- test only against stable flutter / dart versions (not beta, dev)
Related issue: https://github.com/parse-community/Parse-SDK-Flutter/issues/721
Fixed issues mentioned above.
n/a
> ci: optimize CI workflow

- packages/dart/lib/parse_server_sdk.dart
- packages/dart/lib/src/data/parse_core_data.dart
- packages/dart/lib/src/network/parse_client.dart
- packages/dart/lib/src/network/parse_dio_client.dart
- packages/dart/lib/src/objects/parse_file_base.dart
- packages/dart/lib/src/objects/parse_user.dart
- packages/flutter/example/test/data/repository/diet_plan/repository_diet_plan_db_test.dart
- packages/flutter/example/test/data/repository/diet_plan/repository_diet_plan_test.dart
- packages/flutter/example_livelist/lib/main.dart
This PR formats the code as wanted by #725.
Related issue: #725 
Just dart/flutter format
> style: format code to pass lint CI check

- README.md
- packages/dart/README.md
- packages/flutter/README.md
Some general readme maintenance.
Related issue: #n/a
n/a
n/a
> docs: general readme maintenance

- packages/flutter/example/android/.gitignore
- packages/flutter/example/android/app/build.gradle
- packages/flutter/example/android/app/src/debug/AndroidManifest.xml
- packages/flutter/example/android/app/src/main/AndroidManifest.xml
- packages/flutter/example/android/app/src/main/gen/com/example/flutterpluginexample/BuildConfig.java
- packages/flutter/example/android/app/src/main/gen/com/example/flutterpluginexample/Manifest.java
- packages/flutter/example/android/app/src/main/gen/com/example/flutterpluginexample/R.java
- packages/flutter/example/android/app/src/main/java/com/example/flutterpluginexample/MainActivity.java
- packages/flutter/example/android/app/src/main/res/drawable-v21/launch_background.xml
- packages/flutter/example/android/app/src/main/res/values-night/styles.xml
- packages/flutter/example/android/app/src/profile/AndroidManifest.xml
- packages/flutter/example/android/build.gradle
- packages/flutter/example/android/gradle.properties
- packages/flutter/example/android/gradle/wrapper/gradle-wrapper.properties
- packages/flutter/example/android/settings.gradle
Recreated the android application of the flutter example to fix `pub get`.
Related issue: #722 
Just recreated...
The test should fail at the formatting step.
> refactor: update example app to use Android embedding v2 

- .github/workflows/ci.yml
- .gitignore
- tools/flutter-dependencies.sh
Related issue: #732 
After the tests run successfully, the code coverage report is generated and send to codecov.
> ci: add code coverage

- packages/dart/CHANGELOG.md
- packages/flutter/CHANGELOG.md
- Changelogs are restyled according to Parse Org-wide style
- Changelog entry for release 3.1.1 is added
n/a
n/a
> docs: update changelogs

- .github/workflows/release-manual.yml
Just temp. adding dry-run option for release workflow test.
> ci: add dry-run flag for release workflow test

- .github/workflows/release-manual.yml
Dry-run condition doesn't work, wrong syntax
> ci: fix release workflow dry-run condition

- packages/dart/lib/src/base/parse_constants.dart
- packages/dart/pubspec.yaml
- packages/flutter/README.md
- packages/flutter/pubspec.yaml
> ci: bump version to 3.1.1

- .github/workflows/release-manual.yml
Incorrect version for publish action; doesn't support `flutter` argument yet
> ci: upgrade publisher action

- .github/workflows/release-manual.yml
- packages/dart/lib/src/base/parse_constants.dart
- packages/dart/pubspec.yaml
- packages/flutter/pubspec.yaml
Revert dart package version bump since there was no change in dart
> ci: revert version bump; remove dry-run job

- .gitignore
- packages/flutter/example/linux/flutter/ephemeral/.plugin_symlinks/connectivity_plus_linux
- packages/flutter/example/linux/flutter/ephemeral/.plugin_symlinks/path_provider_linux
- packages/flutter/example/linux/flutter/ephemeral/.plugin_symlinks/shared_preferences_linux
Ephemeral symlinks should not be check in.
Add to gitignore.
n/a
> fix: ephemeral linux symlinks checked into repository

- packages/flutter/CHANGELOG.md
release date in flutter changelog is incorrect
update release date in flutter changelog
n/a
> docs: update release date in flutter changelog

- .github/workflows/ci.yml
Related issue: #765 
Make file `flutter-dependencies.sh` executable 
n/a
> ci: failing CI test due to missing file permissions

- .github/workflows/ci.yml
- tools/flutter-dependencies.bat
Related issue: #768 
create file `flutter-dependencies.bat` e call  `flutter-dependencies.bat` on matrix Windows
> ci: test job fails for flutter windows-latest

- packages/dart/pubspec.yaml
- packages/flutter/pubspec.yaml
Remove dependency_overrides in flutter/pubspec.yaml
Related issue: #771 
N/A
N/A
> ci: publishing dart-3.1.2 failed

- packages/flutter/example/test/data/repository/diet_plan/repository_diet_plan_db_test.dart
- packages/flutter/example/test/data/repository/diet_plan/repository_diet_plan_test.dart
fixed the errors of test
-  Add tests
-  Add changes to documentation (guides, repository pages, in-code descriptions)
-  A changelog entry
> test: Fix failing tests in Flutter example project

- .github/workflows/ci.yml
Closes: https://github.com/parse-community/Parse-SDK-Flutter/issues/832
Remove automatic execution of developer script that uses the local dart package instead of the released dart package.
> ci: Remove local dart dependency in flutter CI jobs

- .github/workflows/ci.yml
Closes: https://github.com/parse-community/Parse-SDK-Flutter/issues/832
Add missing dependency installation that was removed in https://github.com/parse-community/Parse-SDK-Flutter/pull/831.
> ci: Add missing dependency installation in CI

- .github/workflows/ci.yml
PR CI runs even if commit is superseded.
Closes: #n/a
Cancel existing CI run on new commit.
> ci: Avoid concurrency in PR CI

- packages/dart/pubspec.yaml
- packages/flutter/pubspec.yaml
> ci: Fix failing CI due to missing platform interface dependencies

- .github/workflows/ci.yml
Closes: #839
start a job to check for any errors when running `dart pub publish --dry-run` 
All set
> ci: Add publish dry-run check for dart package

- .github/workflows/ci.yml
- packages/flutter/CHANGELOG.md
Closes: #856
setup Flutter rather than only Dart
N/A
> ci: Fix failing Flutter dry-run job due to missing changelog version entry

- .github/ISSUE_TEMPLATE/---1-report-an-issue.md
Closes: #862
Add Flutter and Dart versions in the environment section
> ci: Add Flutter and Dart versions to PR template

- .github/workflows/release-automated.yml
- .github/workflows/release-manual.yml
Syntax error in release workflows.
Closes: #881 
Use correct substitute for ternary op.
> ci: Fix release workflows

- .github/workflows/release-manual.yml
Closes: #881 
Fix manual release workflow
> ci: Fix manual release workflow

- .github/workflows/release-automated.yml
- .github/workflows/release-manual.yml
Closes: #881 
Fix release workflows
> ci: Fix release workflow

- CONTRIBUTING.md
Closes: #917
Add `CONTRIBUTING.md`
> docs: Add contribution guide

- packages/flutter/lib/parse_server_sdk_flutter.dart
- packages/flutter/lib/src/notification/parse_notification.dart
- packages/flutter/lib/src/push/parse_push.dart
- packages/flutter/lib/src/storage/core_store_directory_io.dart
- packages/flutter/lib/src/storage/core_store_directory_web.dart
- packages/flutter/lib/src/storage/core_store_sembast.dart
- packages/flutter/lib/src/storage/core_store_shared_preferences.dart
- packages/flutter/lib/src/utils/parse_live_grid.dart
- packages/flutter/lib/src/utils/parse_live_list.dart
Closes: #903
add document
and fix bug `StreamController`
> refactor: Add Flutter code documentation and resolve `StreamController` warning

- .github/workflows/release-manual-docs.yml
API docs not published
Add workflow to publish docs to gh_pages
> ci: Add workflow to publish docs

- .github/workflows/ci.yml
- packages/dart/lib/src/network/dio_adapter_io.dart
- packages/dart/lib/src/network/parse_dio_client.dart
- packages/dart/lib/src/objects/response/parse_exception_response.dart
- packages/dart/pubspec.yaml
- packages/dart/test/parse_query_test.mocks.dart
- packages/flutter/example/pubspec.yaml
- packages/flutter/pubspec.yaml
Closes: #821
Update package_info_plus to ```package_info_plus: ^4.0.2```
> refactor: Update package_info_plus

- packages/flutter/CHANGELOG.md
Typo in changelog
Closes: #n/a
Fix typo in changelog
> docs: Fix changelog typo

- packages/flutter/CHANGELOG.md
Adds missing changelog entry for #1014
> docs: Add feature to README

- packages/dart/CHANGELOG.md
Incorrect changelog entry
Fix package name.
> docs: Fix incorrect changelog entry

- packages/dart/CHANGELOG.md
As release publishing fails, past commits will be published in a joint release. Docs need to reflect that.
> docs: Fix CHANGELOG for dart package
