parse-community/Parse-SDK-Flutter

- lib/src/objects/parse_user.dart
see https://github.com/phillwiggins/flutter_parse_sdk/issues/58
> log in with token

- lib/parse.dart
- lib/src/base/parse_constants.dart
- lib/src/enums/parse_enum_api_rq.dart
- lib/src/objects/parse_file.dart
- lib/src/objects/parse_user.dart
- lib/src/utils/parse_decoder.dart
- pubspec.yaml
Hi Phil,
I am using your sdk to develop an application for our hackathon participants. I ran over a few issues that I fixed and I thought it woud be a good idea to contribute back to this project. Here are my changes:
* Fixed changes on User object not syncing to server due to missing session token when accessing API
* Added the ability to login anonymously by providing "AUTH_DATA" POST data with a unique UUID. Can be extended to allow for facebook and twitter auth in the future
* Added the ability to create a Parse file with a url and name and download the file to temporary storage
* Fixed bug with ParseFile initialized to null _file value.
Let me know if these need work
> Fix User objects not saving, Add support for Parse Files, Anonymous Login

- lib/parse_server_sdk.dart
- lib/src/data/parse_core_data.dart
- lib/src/network/parse_http_client.dart
- lib/src/objects/parse_config.dart
- lib/src/objects/parse_file.dart
- lib/src/objects/parse_function.dart
- lib/src/objects/parse_geo_point.dart
- lib/src/objects/parse_object.dart
- lib/src/objects/parse_user.dart
Make the automatic sending of sessonId in headers optional, can be set globally and later overwritten for each object. Only for User Objects it is always true. So per default this should be the same behaviour as before my changes.
Please review and test :-)
Thanks a lot!
> Make automatic sending of sessionId optional.

- lib/src/base/parse_constants.dart
- lib/src/enums/parse_enum_api_rq.dart
- lib/src/objects/parse_user.dart
> added call to logout endpoint

- lib/src/objects/parse_user.dart
Fix for #83
- Set the return type to Future<ParseResponse>
- sessonId has to be stored and used locally because it is cleared inside the function
- check for username useless
> Fix ParseUser logout() methode

- lib/src/base/parse_constants.dart
- lib/src/objects/parse_user.dart
It is now possible to use the stored user with the stored sessionToken to autologin agian.
> Handle sessionToken correctly in ParseUser

- lib/src/enums/parse_enum_api_rq.dart
- lib/src/objects/parse_user.dart
- pubspec.yaml
This allows third party login in Parse
> Initial loginWith

- lib/parse_server_sdk.dart
- lib/src/base/parse_constants.dart
- lib/src/objects/parse_installation.dart
- pubspec.yaml
This adds ParseInstallation class, one issue I have found is getting the TimeZone from flutter in same way that Parse Server excepts (Europe/Madrid). 
Also an dependency to deviceinfo was added to get Locale value from device using platform code, a better approach would be to add platform specific code in this library instead of using external libraries. This could also solve the problem with TimeZone as we could simply copy the way iOS/Android handles it.
> ParseInstallation implementation

- lib/src/network/parse_query.dart
Added support for Geo Queries:
- whereNear
- whereWithinMiles
- whereWithinKilometers
- whereWithinRadians
- whereWithinGeoBox
> Added support for Geo Queries:

- lib/parse_server_sdk.dart
- lib/src/base/parse_constants.dart
- lib/src/objects/parse_session.dart
Get session data from current session, e.g. expireAt.
> Add support for getting current session

- lib/src/network/parse_query.dart
- lib/src/objects/parse_file.dart
- lib/src/objects/parse_installation.dart
- lib/src/objects/parse_object.dart
- lib/src/objects/parse_user.dart
- lib/src/utils/parse_encoder.dart
- lib/src/utils/parse_utils.dart
ParseQuery - Bugfix query with DateTime
ParseFile - Bugix download function
ParseUser - Remove toJson function (causes crash in ParseUser.currentUser()
ParseEncoder - Bugfix Parse Encoder types
> Bugix ParseQuery, ParseFile, ParseUser, ParseEncoder

- lib/src/base/parse_constants.dart
- lib/src/objects/parse_user.dart
I was needing this change during my app development. Feel free to close this pull request, if you find any issues.
You can refer the following link for more info.
https://github.com/parse-community/parse-server/issues/1097
> Setting installationId in _Session object during sign-up

- README.md
- example/lib/main.dart
- example/pubspec.yaml
> Update Sample Project

- lib/src/objects/parse_geo_point.dart
Update so SubClass of ParseObject uses internal Map for value storage. Changes in v1.0.17 breaks ParseGeoPoint. This is tested and seems to fix the issue.
> Fix lost lat, lng data

- lib/src/network/parse_query.dart
- lib/src/objects/response/parse_response_builder.dart
- Add Support to Relational Queries
https://docs.parseplatform.org/rest/guide/#relational-queries
- Add Support to Counting Objects 
https://docs.parseplatform.org/rest/guide/#counting-objects
>  Add Support to Relational Queries / Counting Objects 

- lib/src/network/parse_live_query.dart
- lib/src/objects/parse_object.dart
Bugfix save and create object / LiveQuery
> Bugfix save and create object / LiveQuery

- README.md
- lib/parse_server_sdk.dart
- lib/src/network/parse_live_query.dart
- lib/src/objects/parse_acl.dart
- lib/src/objects/parse_base.dart
- lib/src/objects/parse_object.dart
- ParseACL implementation
- Updating documentation with instructions for ParseACL
- General documentation review
> ParseACL implementation / Documentation Review

- lib/src/objects/parse_acl.dart
- lib/src/objects/parse_installation.dart
> Some dart linter fixes

- lib/src/objects/parse_user.dart
The `clone` method in `ParseUser` doesn't create a new object like other 'clone' method. This issue leads to response results become the same one. (You can debug into `_handleSingleResult` method.)
I'm not sure this fix is absolutely correct, but this works fine in my project. Please check it carefully.
> Fix user clone issue.

- example/lib/data/base/api_response.dart
- example/lib/main.dart
- example/test/data/repository/diet_plan/repository_diet_plan_api_test.dart
- example/test/data/repository/diet_plan/repository_diet_plan_db_test.dart
- lib/src/network/parse_live_query.dart
- lib/src/network/parse_query.dart
- lib/src/objects/parse_base.dart
- lib/src/objects/parse_config.dart
- lib/src/objects/parse_file.dart
- lib/src/objects/parse_function.dart
- lib/src/objects/parse_installation.dart
- lib/src/objects/parse_object.dart
- lib/src/objects/parse_relation.dart
- lib/src/objects/parse_session.dart
- lib/src/objects/parse_user.dart
- lib/src/objects/response/parse_response_builder.dart
1. Support dirty and unsavedChanges 
2. Optimize some API.
This PR fixed a part of the issue: https://github.com/phillwiggins/flutter_parse_sdk/issues/194
> Optimize Parse object

- lib/src/objects/parse_object.dart
- lib/src/objects/parse_user.dart
1. Fix return result from save method. This is important.
2. Fix unsavedChanges issue in ParseUser login and signUp method.
3. Delete useless and reduplicative decode in ParseUser. Because this is already done in handleResponse method. This also cause wrong unsaved changes.
> Hotfix `save`, `login` and `signUp`

- lib/src/network/parse_live_query.dart
- lib/src/objects/parse_base.dart
- lib/src/objects/parse_installation.dart
- lib/src/objects/parse_object.dart
- lib/src/objects/parse_user.dart
fix installation issue
fix liveQuery.subscribe issue
> same fix for version 1.0.23

- .gitignore
- README.md
- example/lib/domain/constants/application_constants.dart
- lib/src/base/parse_constants.dart
- lib/src/network/parse_query.dart
- lib/src/objects/parse_object.dart
- lib/src/objects/parse_user.dart
- lib/src/objects/response/parse_response_builder.dart
```
final ParseResponse response = await parseObject.distinct("name");
// response.results:["zhao","qian","sun","li"];
```
> add distinct function

- lib/src/network/parse_live_query.dart
When `autoSendSessionId: true`, it always sets the sessionToken header, even if `null`. However, when `null`, it throws an exception due to its unexpected type and breaks live query.
Below is the Flutter output when this happens:
```
I/flutter (12537): LiveQuery: : ConnectMessage: {op: connect, applicationId: myAppId, masterKey: 123456, sessionToken: null}
I/flutter (12537): LiveQuery: : SubscribeMessage: {op: subscribe, requestId: 1, query: {className: Diet_Plans, where: {objectId: 2pNUgv1CKA}}, sessionToken: null}
I/flutter (12537): LiveQuery: : Listen: {"op":"error","error":"Invalid type: null (expected string)","code":1,"reconnect":true}
```
Fixes #196
> fix(LiveQuery): Session token null when subscribing

- README.md
- lib/src/objects/parse_user.dart
Previous Pull Request: https://github.com/phillwiggins/flutter_parse_sdk/pull/231
Pull Request Details:
var user = ParseUser("TestFlutter", "TestPassword123", "TestFlutterSDK@gmail.com")
..set("userLocation", "FlutterLand");
Currently ParseUser Signup only writes username, email Id, password to the User database and doesn't accept additional columns added through the .set(key, value) API even though the data is available in objectData.
Modifying the signup() code to accommodate for the same.
> Allow adding additional columns to ParseUser through the set call

- lib/src/objects/parse_base.dart
- lib/src/objects/parse_file.dart
`ParseObject` should be a table in database on parse server, but `ParseFile` can't be a table.
I had found implementation of `PFFileObject` in iOS/OSX SDK, it's NOT a subclass of 'PFObject'.
When `ParseFile` extends from `ParseObject`, it cause an infinite loop in `save()` method.
> ParseFile should NOT extends ParseObject.

- README.md
- lib/src/network/parse_live_query.dart
- lib/src/network/parse_query.dart
- fix some issues
- Update README.md
> fix some issues / Update README.md

- lib/parse_server_sdk.dart
- lib/src/objects/parse_base.dart
- lib/src/objects/parse_merge.dart
The method of setAdd, setRemove, setAddAll, setRemoveAll, Increment, AddUnique, AddRelation, RemoveRelation can be merged between the same operation and some other operation. Implementation method reference iOS SDK. I do this by Implementing a tool class in "parse_merge.dart" and calling the "mergeWithPrevious" Method in the set method which implemented in parse_base.dart.
> MergeWithPrevious change

- lib/src/network/parse_live_query.dart
- lib/src/network/parse_query.dart
- lib/src/objects/parse_base.dart
> Fix OrderBy multiple columns

- lib/src/objects/parse_function.dart
hi ! brother,I'm come again !
today,When I used ParseCloudFunction, I encountered a problem, the headers parameter failed,and  I fixed it.
code:
```
final ParseCloudFunction parseCloud = ParseCloudFunction('functionName');
final Map<String, String> params = <String, String>{
'objectId': '5b625c781235522020dbbad9c',
};
final Map<String, String> headers = <String, String>{
"content-type": 'application/json'
};
final ParseResponse result =
await parseCloud.execute(parameters: params,headers: headers);
```
from
request.headers :{content-type: text/plain; charset=utf-8}
now 
request.headers :{content-type: application/json; charset=utf-8}
and the function it's work
At last :look forward to your reply
> fix ParseCloudFunction execute and executeObjectFunction headers fail

- lib/parse_server_sdk.dart
- lib/src/network/parse_live_query_web.dart
- lib/src/network/parse_query.dart
- pubspec.yaml
Adds LiveQuery support for Flutter Web using WebSocket implementation from `dart:html` package
> Add LiveQuery support for Flutter Web

- .gitignore
- lib/src/objects/parse_installation.dart
- lib/src/objects/parse_object.dart
- lib/src/objects/parse_session.dart
- pubspec.yaml
hi,brother!
Here are some changes I made.
* Add a header to the ParseObject.update and ParseInstallation.create
It's fix some bug about when I use them,return "request body is empty"
> Actually:[For POST and PUT requests, the request body must be JSON, with the Content-Type header set to application/json.](https://docs.parseplatform.org/rest/guide/#request-format),but I don't know much about this.I am worried that if I change all of them, there will be some errors that I don't understand, so I only changed the method I am currently using.
* ParseSession add set installationId
so now:
```
final ParseSession parseSession = ParseSession();
var res = await parseSession.getCurrentSessionFromServer();
if (res.success) {
final ParseInstallation installation =
await …
```
> ParseObject.update/ParseInstallation.create/ParseSession.installationId

- lib/src/objects/parse_user.dart
I needed to forget session id and delete local data after calling ParseUser.destroy (as while the call is in progress, ParseUser.currentUser could be called and session id would be renewed).
> Refactored ParseUser.logout - resetting session id and deleting local data as a separate functions

- README.md
Current documentation has deprecated methods usage.
> Updated Live Queries related documentation

- CHANGELOG.md
- README.md
- lib/parse_server_sdk.dart
- lib/src/base/parse_constants.dart
- lib/src/objects/parse_base.dart
- pubspec.yaml
Small change, but I think it's a good practice to return a concrete type instead of dynamic when we can.
Additionally, for developers who have `implicit-casts` set to `false` in their analysys_options.yaml, from this point on they won't have to write code like this:
`String name = get<String>('name') as String;`
but instead will be able to do just:
`String name = get<String>('name');`
Thanks for making this package btw! :)
> Specifying return type of get<T> as T instead of dynamic

- CHANGELOG.md
- README.md
- lib/parse_server_sdk.dart
- lib/src/base/parse_constants.dart
- lib/src/network/parse_live_query.dart
- pubspec.yaml
This change provides "an event or a way to detect when connection is lost while using LiveQuery" as requested in #261
Please consider merging this change.
Reopened from #313.
> Live query connection stream

- lib/src/network/parse_query.dart
Added a second constructor to ParseQuery for creating OR Queries.
#213 
Tested with basic queries.
Works with live query, too.
> Parsequery OR

- lib/src/network/parse_query.dart
I could not find any way to copy a QueryBuilder.
So I added a constructor that takes an QueryBuilder as a base.
This is a deep copy.
Tested only with basic queries.
#319
> added QueryBuilder.copy(QueryBuilder<T> query)

- lib/src/network/parse_live_query.dart
Should fix https://github.com/parse-community/Parse-SDK-Flutter/issues/330
(and some format changes by my IDE... Is this a problem?)
> LiveQueryController: connect at init

- lib/src/network/parse_live_query.dart
- lib/src/network/parse_query.dart
- lib/src/objects/parse_object.dart
- lib/src/utils/parse_live_list.dart
Might be a solution for #335 .
Further testing in complex applications is required.
> Added generics to Query/LiveQuery

- lib/src/utils/parse_live_list.dart
When no object fits the query, the the returned list is null.
This should fix some NullPointer errors.
> LiveQuery: list is null fixes

- lib/src/utils/parse_live_list.dart
Fixes #341 
It seems like `subscription.on(LiveQueryEvent.update` reuses an existing object.
> Fix: LiveList reorder on update(#341)

- lib/src/utils/parse_live_list.dart
This should fix #347.
It's not optimal jet as some network traffic is avoidable.
Listening for updates in included objects is jet not possible.
I might contribute this two changes soon, too.
(Note: https://github.com/parse-community/Parse-SDK-Flutter/commit/a30de875128e03496996ea05ef83291fe4d5f802 is not related to #347 but it fixes an bug, where an old widget state is displayed, when the order of an object changes, but not the position in the list. If it sounds confusing, just ignore this.)
**EDIT:**
See https://github.com/parse-community/Parse-SDK-Flutter/pull/348#issuecomment-609013051 for update.
> Fix for #347 (include in LiveList)

- README.md
- lib/src/utils/parse_live_list.dart
This is the PR mentioned in https://github.com/parse-community/Parse-SDK-Flutter/pull/348#issuecomment-609013051.
Have a look in the README changes for further information.
Note: Currently ParseLiveList wont update your sub-objects after your client reconnects to the web.
> LiveList autoupdate included sub-objects

- README.md
- lib/src/utils/parse_live_list.dart
This addition should update sub-objects after a reconnect automatically.
I have only done basic testing.
> LiveList: sync subObjects after reconnect

- example/lib/data/base/api_error.dart
- example/lib/data/base/api_response.dart
- example/lib/data/repositories/diet_plan/provider_db_diet_plan.dart
- example/lib/data/repositories/user/provider_db_user.dart
- lib/src/objects/parse_error.dart
- lib/src/objects/response/parse_exception_response.dart
- lib/src/utils/parse_logger.dart
Closes: https://github.com/parse-community/Parse-SDK-Flutter/issues/351
> Issue-351: Replaced isTypeOfException with Exception

- README.md
- lib/parse_server_sdk.dart
- lib/src/data/parse_core_data.dart
- lib/src/data/parse_subclass_handler.dart
- lib/src/network/parse_live_query.dart
- lib/src/network/parse_live_query_web.dart
- lib/src/network/parse_query.dart
- lib/src/objects/parse_user.dart
- lib/src/storage/core_store_sem_impl.dart
- lib/src/utils/parse_decoder.dart
As described in https://github.com/parse-community/Parse-SDK-Flutter/issues/350#issuecomment-614071136, I have now worked with this RegisterSubClass feature for a while.
While testing, I haven't encountered a single bug.
I think, this feature is ready for merging.
For more details about RegisterSubClass, have a lock into the new README.
This PR also contains a Fix for a Bug, where CoreStore would not work when using the sembast implementation in an macos app.
And a fix for #364 / #256.
I have created one PR for this three changes. If this is a problem, I can create separated ones as well.
> RegisterSubClass and smaler changes

- lib/src/objects/parse_installation.dart
- lib/src/objects/parse_user.dart
Related issue: https://github.com/parse-community/Parse-SDK-Flutter/issues/373
+ Save ParseInstallation in ParseCoreData after creating new instance.
+ ParseUser.login() now send installationId (this way, no new session is created at every login event)
> [Fix] InstallationId storage and User login

- lib/src/utils/parse_live_list.dart
ParseLiveList listens on included objects. LiveQuery is currently not able to do this due to the server implementation.
As this is an useful feature, I added LiveElement.
ParseLiveElement is build on to of ParseLiveListElement and can be used like a mix of LiveQuery and ParseLiveListWidget.
You can get the current ParseObject through a stream.
> ParseLiveElement

- README.md
- lib/src/network/parse_query.dart
- News methods for ParseQuery -  whereMatchesKeyInQuery and whereDoesNotMatchKeyInQuery
- README.md update
Note: I started updating the Plugin documentation using the Parse JS documentation as a base.
> News methods for ParseQuery -  whereMatchesKeyInQuery and whereDoesNotMatchKeyInQuery

- README.md
- lib/src/utils/parse_login_helpers.dart
- Update README to show how to get google login attributes for parse
> Add google login helper

- lib/parse_server_sdk.dart
- lib/src/objects/parse_installation.dart
- lib/src/storage/core_store_sem_impl.dart
Fixes `Unsupported operation: Platform._operatingSystem` as described in #385 .
dart:io 's Platform.isX is unsupported in web.
The recommended way is using kIsWeb from flutter foundations: https://github.com/flutter/flutter/issues/36126.
This does not enable sembast usage in web. It still needs the [sembast_web package](https://pub.dev/packages/sembast_web).
(Same as #391 but against the right branch)
> [web] Check web before Platform.isX

- README.md
- lib/parse_server_sdk.dart
- lib/src/objects/parse_installation.dart
Adds to #392 to further improve web compatibility.
General web support issue: #385
Replaces following incompatible packages only for web:
Replaced by `ui.window.locale.languageCode` from dart:ui package.
This outputs the language as ("en_US", "en_GB"), same as on Android with Devicelocale (Devicelocale returns - dashes for iOS).
Here I opted to remove all the properties coming from PackageInfo.
Parsing the yaml file and injecting them inside the app somehow could work, but I would rather wait and hope for PackageInfo to support web sometime in the future.
Pending Readme changes.
> Make web compatible calls for locale and skip PackageInfo

- lib/src/utils/parse_live_list.dart
The lazy loading of ParseLiveList is a feature that allows to display long lists as quick as possible.
But for short lists it takes some extra time.
This is a first implementation that allows to turn of lazy loading.
Setting `lazyLoading=false` should disable lazy loading.
In my (quick) tests everything worked as expected. However, further testing is highly appreciated.
> ParseLiveList: option to turn off lazy loading

- lib/src/utils/parse_live_list.dart
In theory this should not make any difference. In practise sometimes an error gets thrown:
> The following NoSuchMethodError was thrown while finalizing the widget tree:
> The method 'dispose' was called on null.
> Receiver: null
> Tried calling: dispose()
> ParseLiveList: NoSuchMethodError

- README.md
- lib/parse_server_sdk.dart
- lib/src/base/parse_constants.dart
- lib/src/data/parse_core_data.dart
- lib/src/data/parse_subclass_handler.dart
- lib/src/objects/parse_file_base.dart
- lib/src/objects/parse_file_web.dart
- lib/src/objects/parse_object.dart
- lib/src/utils/parse_decoder.dart
- lib/src/utils/parse_encoder.dart
This pr is part of #385 and enables file support for flutter web.
The implementation has been described [here](https://github.com/parse-community/Parse-SDK-Flutter/issues/385#issuecomment-670496510), for a small example, have a look at the README.
In my application everything worked as expected.
> File Support for web

- README.md
I've decided to create an example for uploading a selected image.
As this is a common question in issues and the there are some useful tricks reducing the required code.
> add an other file example to README

- lib/src/objects/parse_file_web.dart
This probably breaks the extension at the uploaded file, but otherwise the upload would fail with a server error.
I think this is the better choice.
> Web file upload: set content type to "text/plain" incase neighter name nor url is set

- README.md
- lib/parse_server_sdk.dart
- lib/src/data/parse_core_data.dart
- lib/src/network/parse_live_query.dart
- lib/src/network/parse_live_query_web.dart
LiveQuery reconnecting intervals should be adjustable at Parse().initialize().
Further information in the README.
And I've noticed, I missed parseFileConstructor at Parse().initialize(). Oops.
> LiveQuery reconnecting intervals

- lib/parse_server_sdk.dart
- lib/src/base/parse_constants.dart
- lib/src/data/parse_core_data.dart
- lib/src/data/parse_subclass_handler.dart
- lib/src/objects/parse_installation.dart
- lib/src/storage/core_store_sem_impl.dart
- lib/src/utils/parse_utils.dart
I think, using less libraries is always a good idea.
> replace kIsWeb with its definition

- lib/parse_server_sdk.dart
- lib/src/objects/parse_installation.dart
- pubspec.yaml
- test/parse_client_configuration_test.dart
- test/parse_query_test.dart
Devicelocale is not maintained a lot and currently throws errors for me when building a Android APK release.
It was only used in one place for the installation, and can be replaced by Platform.localeName (not working for Web, so keeping the alternate web call).
Now the package has one less dependency on a not greatly maintained package.
A throughout example or possibilities to get Locale: https://stackoverflow.com/a/62825776/1387765
Also replaces test (dart only), by flutter_test to fix tests.
> Replace devicelocale by Platform.localeName call

- README.md
- lib/parse_server_sdk.dart
- lib/parse_server_sdk_dart.dart
- lib/src/storage/core_store_sem_impl.dart
- pubspec.yaml
This is pretty much the same PR as @nstrelow's  #394.
Please have a look at  #394 for a detailed explanation of the problem.
I think, although it's not optimal,  not encrypting the database is the best trade we can make.
As far as I know, this should add full web support to the SDK. (#385)
> Add WEB-support for CoreStoreSembastImp

- packages/dart/lib/src/utils/parse_live_list.dart
- packages/dart/lib/src/utils/parse_utils.dart
Fixes a bug, where the throw lets the function fail and does not add a error to the stream.
> Fix throw in LiveList

- .travis.yml
- packages/dart/lib/src/objects/parse_user.dart
- packages/flutter/lib/parse_server_sdk.dart
Potential fix for #444.
But some more testing is required.
> ParseUser: store password in field

- packages/dart/lib/src/utils/parse_live_list.dart
- packages/flutter/README.md
- packages/flutter/lib/src/utils/parse_live_list.dart
This adds support for adding custom columns to the LiveList, that get loaded at the initial query.
TODOS:
> LiveList: preloadedColumns

- README.md
- packages/dart/README.md
- packages/flutter/README.md
> improve Readme for 1.0.28

- packages/dart/lib/src/objects/parse_user.dart
By setting [allowWithoutEmail] to `true`, you can sign up without setting an email.
Fix #465
> allow signup without email

- packages/dart/lib/src/objects/parse_user.dart
> SignUp encoding data to JSON

- packages/dart/README.md
- packages/flutter/README.md
> Add disclaimer to not use Masterkey on client side

- packages/dart/lib/src/network/parse_query.dart
Fix bug where whereMatchesKeyInQuery cant be used when using different object classes.
> Querybuilder: whereMatchesKeyInQuery bugfix

- packages/dart/lib/src/objects/parse_base.dart
- packages/dart/lib/src/objects/parse_file_base.dart
- packages/dart/lib/src/objects/parse_installation.dart
- packages/dart/lib/src/objects/parse_object.dart
Adds support for custom object IDs that are generated on the client side and sent during creation of Parse objects.
This option needs to be enabled on the Parse server. 
Example from Back4app documentation: https://www.back4app.com/docs/platform/custom-parse-options
> Add support for custom object IDs

- packages/dart/lib/src/objects/parse_user.dart
- packages/flutter/pubspec.yaml
This is a fix for #490.
As reported by @gorillatapstudio and @nstrelow, it does not seem to be possible to add custom headers to the parse-server instance when using back4app. As the `X-Parse-Installation-Id` header is not allowed by default, user login does not work on web due to CORS restrictions.
This PR adds the option to prevent the SDK from using this header.
There should be no breaking change, as the default behavior did not change.
> added doNotSendInstallationID parameter to user functions

- packages/dart/lib/src/objects/parse_user.dart
See #501 for more information.
> Show a console log if ParseUser.signUp was called without a provided email

- packages/dart/lib/src/objects/parse_user.dart
Replace #507 
Add username, password and email as optional params for ParseUser.loginWith(...). Related: #506
> ParseUser.loginWith(...) username, password, email

- packages/dart/README.md
- packages/dart/lib/parse_server_sdk.dart
- packages/flutter/README.md
- packages/flutter/example/lib/domain/constants/application_constants.dart
- packages/flutter/example/lib/main.dart
- packages/flutter/example/lib/pages/decision_page.dart
- packages/flutter/example/test/data/repository/repository_mock_utils.dart
- packages/flutter/lib/parse_server_sdk.dart
See #417 and #473 for more information.
> remove missleading masterkey documentation

- packages/dart/CHANGELOG.md
- packages/dart/README.md
- packages/dart/lib/parse_server_sdk.dart
- packages/dart/lib/src/base/parse_constants.dart
- packages/dart/lib/src/data/parse_core_data.dart
- packages/dart/lib/src/network/parse_dio_client.dart
- packages/dart/lib/src/network/parse_live_query.dart
- packages/dart/lib/src/network/parse_query.dart
- packages/dart/lib/src/objects/parse_acl.dart
- packages/dart/lib/src/objects/parse_installation.dart
- packages/dart/lib/src/storage/core_store_sem_impl.dart
- packages/dart/lib/src/utils/parse_login_helpers.dart
- packages/dart/pubspec.yaml
- packages/flutter/CHANGELOG.md
- packages/flutter/README.md
- packages/flutter/example/pubspec.yaml
- packages/flutter/lib/parse_server_sdk.dart
- packages/flutter/pubspec.yaml
* Fix CoreStoreSembastImp with no default passwod causes error in Flutter Package
* Fix ParseACL with no default value in setReadAccess and setWriteAccess
* Add method excludeKeys: Exclude specific fields from the returned query
* Updated Dependencies version in pubspec.yaml
* Fix typo in the ParseConnectivity provided Error message parse_live_query.dart
> Fix CoreStoreSembastImp / Fix ParseACL / New Query Method / Updated Dependencies version / Fix error message parse_live_query.dart

- packages/dart/lib/src/objects/parse_user.dart
The containsKey check is on the wrong key (keyVarObjectId) instead of (keyParamSessionToken) - therefore it fails on null safety, if the sessionToken is not provided in responseData (for example in case of signUp)
> :bug: containsKey on wrong key

- packages/dart/lib/src/utils/parse_live_list.dart
ParseLiveListWidget is sending the wrong GET request if lazyloading is enabled and no order limiter is set.
We have to check if there is a key to send
> fixes #653

- packages/dart/lib/src/network/parse_query.dart
Fixes https://github.com/parse-community/Parse-SDK-Flutter/issues/661
> first: Correct return type

- README.md
- CI badge in README still points to TravisCI, should point to GitHub CI
- Links to pub.dev are broken
Related issue: #n/a
Fix issues mentioned above.
n/a
> docs: fix CI badge

- .github/workflows/release-manual.yml
- .github/workflows/release-trigger.yml
Add manual release workflow per package.
Add workflow that requests tag + package input to trigger the appropriate publishing process.
n/a
> ci: add manual release workflow

- .github/workflows/release-automated.yml
After manually creating a release, publishing to the pub.dev registry is an additional manual step.
Autoamtically triggers the release workflow after creating a release.
The package to publish is determined by the created tag:
- `dart-#.#.#` -> publish dart package
- `flutter-#.#.#` -> publish flutter package
n/a
> ci: add auto-release

- packages/dart/pubspec.yaml
- packages/flutter/pubspec.yaml
Bumping the versions, since #734 did not cover it.
Related issue: #733 
~Left the `parse_server_sdk` dependency in the flutter package at `^3.1.0`.~
Not sure if the title really fits. Feel free to edit. `ci:` seems best to me.
n/a
> ci: bump versions for next release

- packages/dart/CHANGELOG.md
- packages/dart/lib/src/utils/parse_encoder.dart
- packages/dart/pubspec.yaml
- packages/dart/test/parse_encoder_test.dart
Solve the parseEncode problem in list and map
and test added
Related issue: https://github.com/parse-community/Parse-SDK-Flutter/issues/788
The ```full: full``` was added for when we use the list and map in parseEncode and toJson
> fix: Custom JSON encoder for List and Map doesn't work correctly in `full` mode

- packages/dart/CHANGELOG.md
- packages/dart/lib/src/base/parse_constants.dart
- packages/dart/lib/src/objects/parse_base.dart
- packages/dart/pubspec.yaml
remove protected in ```toJson``` for use externally
Closes: #616
only remove protected in ```toJson```
> feat: Add `ParseObject.toJson()` to create a JSON representation

- packages/dart/CHANGELOG.md
- packages/dart/lib/src/base/parse_constants.dart
- packages/dart/lib/src/objects/parse_object.dart
- packages/dart/pubspec.yaml
- packages/dart/test/parse_object_test.dart
fix include in get object
Closes: #813
Use Parse SDK built-in functions to solve the problem
> fix: Include option in `getObject` feature is not working

- packages/dart/CHANGELOG.md
- packages/dart/lib/src/base/parse_constants.dart
- packages/dart/lib/src/objects/parse_base.dart
- packages/dart/pubspec.yaml
```fromJson``` not work in ```save```
Closes: #688
added ```_unsavedChanges``` in fromJson  for fix bug.
> fix: `ParseObject.fromJson` does not send proper payload to server

- packages/dart/CHANGELOG.md
- packages/dart/lib/src/base/parse_constants.dart
- packages/dart/lib/src/objects/parse_base.dart
- packages/dart/pubspec.yaml
fix save user
Closes: #819
Use the new method to send Json in ```fromJson```
> fix: `ParseUser.save` fails when user is logged in

- packages/dart/CHANGELOG.md
- packages/dart/lib/src/base/parse_constants.dart
- packages/dart/lib/src/network/parse_dio_client.dart
- packages/dart/pubspec.yaml
When an error occurs, the Dio error object could hold null properties  causing the error (Type 'Null' is not a subtype of type 'Object')
Closes: [#774](https://github.com/parse-community/Parse-SDK-Flutter/issues/774)
Add null aware operator `??`:
``` dart
on dio.DioError catch (error) {
return ParseNetworkResponse(
data: error.response?.data ?? _fallbackErrorData,
statusCode: error.response?.statusCode ?? ParseError.otherCause,
);
}
```
All set
> fix: Dio error holds a reference to null values

- packages/dart/CHANGELOG.md
- packages/dart/lib/src/base/parse_constants.dart
- packages/dart/lib/src/objects/parse_object.dart
- packages/dart/pubspec.yaml
Closes: [#828](https://github.com/parse-community/Parse-SDK-Flutter/issues/828)
Use `assert()` to make sure that the `objectId` is valid and can be used
> fix: Updating and deleting a ParseObject sends requests even if object ID is null

- packages/flutter/CHANGELOG.md
- packages/flutter/lib/src/storage/core_store_directory_io.dart
- packages/flutter/pubspec.yaml
- packages/flutter/test/src/storage/core_store_directory_io_test.dart
Closes: [#791](https://github.com/parse-community/Parse-SDK-Flutter/issues/791)
Using LibraryDirectory as a path for the database.
This is a breaking change for **_ios_** platform because the SDK now will look for the "parse.db" in the `LibraryDirectory` rather than the `ApplicationDocumentsDirectory`.
We can support the old directory path by doing something like:
``` dart
Future<String> getDatabaseDirectory() async {
if (Platform.isIOS) {
if(await _isDatabaseFileExistsInOldPath()){
return (await path_provider.getApplicationDocumentsDirectory()).path;
}
return (await path_provider.getLibraryDirectory()).path;
} else {
return (await path_provider.getApplicationDocumentsDirectory()).path;
}
}
Future<bool> _isDatabaseFileExistsInOldPath() async {
final oldIosDatabaseDirPath =
(await …
```
> fix: Parse SDK internal database file `parse.db` is accessible for app user on iOS and may be accidentally deleted

- .github/workflows/ci.yml
Closes: #847
start a job to check for any errors when running `dart pub publish --dry-run` For the Flutter package
Merge this PR first #846
> ci: Add `pub publish --dry-run` for Flutter package

- packages/dart/CHANGELOG.md
- packages/dart/lib/src/base/parse_constants.dart
- packages/dart/lib/src/objects/parse_object.dart
- packages/dart/pubspec.yaml
- packages/dart/test/src/objects/parse_object/parse_object_save_test.dart
Closes: #854
Consider the `totalResponse` from the batch as unsuccessful
``` dart 
// if any request in a batch requests group fails,
// then the overall response will be considered unsuccessful.
totalResponse.success = false;
```
Merge #858 first, then I will add a change log entry with that PR, so we publish two fixes in one version.(4.0.1)
> fix: Attempt to save `ParseObject` even if its nested `ParseObject` failed to save

- .github/workflows/ci.yml
- packages/dart/README.md
- packages/flutter/README.md
CI is only testing against one (presumably the latest) dart framework version.
Closes: #873 
- Add Dart SDK version matrix for testing of all currently officially supported Dart SDK versions.
- Add support policy by adding a compatibility table to the README of each package.
> ci: Add Dart / Flutter version matrix

- packages/flutter/README.md
- packages/flutter/test/src/storage/core_store_directory_io_test.dart
Closes: #875
Remove the optional parameter because it is not supported on Flutter versions >=3.3.0.
This change will not impact the tests, as the default value for this parameter is false. See the [docs](https://api.dart.dev/stable/3.0.0/dart-io/File/createSync.html)
> test: Remove optional `exclusive` parameter from core store test

- .github/workflows/release-automated.yml
- .github/workflows/release-manual.yml
Publishing to pub.dev fails due to missing credentials of the Google Account to publish. Added Google domain verification for publisher, but workflow still fails.
Trying to upgrade publish action k-paxian/dart-package-publisher to latest version to see if that fixes the issue.
> ci: Upgrade publish action

- packages/dart/CHANGELOG.md
- packages/dart/lib/src/base/parse_constants.dart
- packages/dart/pubspec.yaml
- packages/flutter/pubspec.yaml
The collection dependency ^1.17.1 makes the Parse Dart SDK incompatible with the `flutter_test` dependency of Flutter <3.10.0. To continue support Flutter >= 3.3, the collection dependency needs to be downgraded.
Downgrade collection dependency to ^1.16.0.
> feat: Downgrade collection dependency to `^1.16.0` for compatibility with Flutter >=3.3

- .github/workflows/release-automated.yml
- .github/workflows/release-manual.yml
Closes: #881
Using the recommended solution by the Flutter team [publishing packages using GitHub actions](https://dart.dev/tools/pub/automated-publishing#publishing-packages-using-github-actions)
@mtrezza There are some steps you need to do in the pub.dev admin tab to enable this.
On the Dart SDK admin tab add the following 
On the Flutter SDK admin tab add the following 
Make sure to follow this [hardening security with tag-protection rules on github](https://dart.dev/tools/pub/automated-publishing#hardening-security-with-tag-protection-rules-on-github)
> ci: Use `dart pub publish` command for release workflows

- .github/workflows/release-manual.yml
Input fields missing for manual release workflow; these can be removed later so that only the tag needs to be chosen, but for Flutter 5.0.0 release, they are required.
Closes: #881 
Add input tags in workflow.
> ci: Fix manual release workflow

- .github/pull_request_template.md
- Any contribution is under this [license](https://github.com/parse-community/parse-server/blob/master/LICENSE).
License link incorrect.
Closes: #n/a
> docs: Fix license link in PR template

- packages/dart/example/main.dart
- packages/dart/example/pubspec.yaml
add pubspec in dart example and fix main.dart example warning
Closes: #905
n/a
n/a
> refactor: Add pubspec in dart example

- packages/dart/CHANGELOG.md
Dart release date in changelog incorrect.
Closes: #905 
Fix Dart release date in changelog.
> docs: Update dart 5.1.1 release date

- packages/flutter/CHANGELOG.md
- packages/flutter/PUSH.md
- packages/flutter/lib/parse_server_sdk_flutter.dart
- packages/flutter/lib/src/notification/parse_notification.dart
- packages/flutter/lib/src/push/parse_push.dart
- packages/flutter/pubspec.yaml
Closes: #913 and #742
This feature is implemented based on the logic of Parse Android
> feat: Add support for push notifications via `ParsePush`, `ParseNotification` 

- packages/dart/CHANGELOG.md
- packages/dart/lib/src/base/parse_constants.dart
- packages/dart/lib/src/network/parse_query.dart
- packages/dart/pubspec.yaml
- packages/dart/test/src/network/parse_query_test.dart
Re-open PR: #943
Closes: #939
Fix bug in JSON creation when `whereMatchesQuery` is used.
> fix: Malformed JSON in `whereMatchesQuery`

- packages/dart/CHANGELOG.md
- packages/dart/lib/src/base/parse_constants.dart
- packages/dart/lib/src/network/parse_live_query.dart
- packages/dart/pubspec.yaml
- packages/dart/test/src/network/parse_live_query_test.dart
- packages/dart/test/test_utils.dart
Closes: #975
add `installationId` in LiveQuery `connect`.
> feat: Add `installationId` in LiveQuery connect

- packages/dart/CHANGELOG.md
- packages/dart/lib/parse_server_sdk.dart
- packages/dart/lib/src/base/parse_constants.dart
- packages/dart/lib/src/objects/parse_file.dart
- packages/dart/lib/src/objects/parse_file_web.dart
- packages/dart/lib/src/objects/parse_x_file.dart
- packages/dart/pubspec.yaml
Add `ParseXFile` for support [`XFile`](https://pub.dev/documentation/cross_file/latest/cross_file/XFile-class.html).
Closes: #989
> feat: Add `ParseXFile` for cross-platform `XFile` support

- .github/workflows/ci.yml
Codecov upload is failing.
Add global upload token to GitHub org.
> ci: Fix failing Codecov upload

- packages/dart/CHANGELOG.md
- packages/dart/lib/src/base/parse_constants.dart
- packages/dart/lib/src/objects/parse_file.dart
- packages/dart/lib/src/objects/parse_x_file.dart
- packages/dart/pubspec.yaml
- packages/dart/test/src/objects/parse_file_test.dart
- packages/dart/test/src/objects/parse_x_file_test.dart
Select the file name from the input name instead of file
Closes: #1011
n/a
> fix: Select input name instead of file in `ParseFile`

- .github/workflows/ci.yml
- packages/flutter/CHANGELOG.md
- packages/flutter/README.md
- packages/flutter/example/lib/domain/utils/db_utils.dart
- packages/flutter/example/test/data/repository/repository_mock_utils.dart
- packages/flutter/lib/parse_server_sdk_flutter.dart
- packages/flutter/pubspec.yaml
- packages/flutter/test/src/storage/core_store_directory_io_test.dart
This release removes support for Flutter 3.10, 3.13
Closes: #1010
n/a
> feat: Removes support for Flutter `3.10`, `3.13`

- .github/workflows/release-automated.yml
> ci: Fix failing release due to unsupported dart version
